name: Debug github Action with frp tunnel
description: Debug github Action with frp tunnel
author: neighbads

branding:
  color: green
  icon: github

inputs:
  frp_server_addr:
    description: The address of the frp server
    required: true
  frp_server_port:
    description: The port of the frp server
    required: true
  frp_token:
    description: The token of the frp server
    required: true
  remote_port:
    description: The port of the remote server
    required: true
  frp_version:
    description: The version of the frp
    required: false
    default: "0.58.1"

runs:
  using: composite
  steps:
    - name: add admin user
      shell: pwsh
      run: |
        # Generate a 16-character random password
        $Password = -join ((33..126) | Get-Random -Count 14 | ForEach-Object { [char]$_ })
        # --- IMPORTANT ---
        # The generated password will be printed to the action log below.
        # You will need this password to connect remotely.
        echo "===================================================================="
        echo "Generated Admin Password: $Password"
        echo "===================================================================="
        # Create the user with the generated password
        net user admin $Password /add
        if ($LASTEXITCODE -ne 0) {
          echo "Failed to create user."
          exit 1
        }
        # Add the user to the administrators group
        net localgroup administrators admin /add
        if ($LASTEXITCODE -ne 0) {
          echo "Failed to add user to administrators group."
          exit 1
        }
        echo "User 'admin' created and added to administrators group successfully."

    - name: enable remote desktop
      shell: pwsh
      run: |
        $service = Get-Service -Name TermService
        if ($service.Status -ne 'Running') {
          echo "TermService is not running, starting it."
          Start-Service -Name TermService
        }

    - name: download frp and setup frp config
      shell: pwsh
      run: |
        Get-Location
        $frp_version = "frp_${{ inputs.frp_version }}_windows_amd64"
        # download frp binary
        Invoke-WebRequest -Uri https://github.com/fatedier/frp/releases/download/v${{ inputs.frp_version }}/$frp_version.zip -OutFile "$frp_version.zip"
        Expand-Archive -Path "$frp_version.zip" -DestinationPath .
        # write frp config
        Write-Output "serverAddr = `"${{ inputs.frp_server_addr }}`"" | Out-File -FilePath "$frp_version/action_debug.toml" -Encoding Default
        Write-Output "serverPort = ${{ inputs.frp_server_port }}" | Out-File -Append -FilePath "$frp_version/action_debug.toml" -Encoding Default
        Write-Output "auth.token = `"${{ inputs.frp_token }}`"" | Out-File -Append -FilePath "$frp_version/action_debug.toml" -Encoding Default
        Write-Output "transport.tls.enable = true" | Out-File -Append -FilePath "$frp_version/action_debug.toml" -Encoding Default
        Write-Output "[[proxies]]" | Out-File -Append -FilePath "$frp_version/action_debug.toml" -Encoding Default
        Write-Output "name = `"github-runner-${{ github.run_id }}`"" | Out-File -Append -FilePath "$frp_version/action_debug.toml" -Encoding Default
        Write-Output "type = `"tcp`"" | Out-File -Append -FilePath "$frp_version/action_debug.toml" -Encoding Default
        Write-Output "localIP = `"127.0.0.1`"" | Out-File -Append -FilePath "$frp_version/action_debug.toml" -Encoding Default
        Write-Output "localPort = 3389" | Out-File -Append -FilePath "$frp_version/action_debug.toml" -Encoding Default
        Write-Output "remotePort = 20039" | Out-File -Append -FilePath "$frp_version/action_debug.toml" -Encoding Default
        # echo the content of the file
        Get-Content -Path "$frp_version/action_debug.toml"
        # start frp
        &"./$frp_version/frpc.exe" -c "$frp_version/action_debug.toml"