name: Debug github Action with frp tunnel

on:
  push:
    branches:
      - main

env:
  FRP_SERVER_ADDR: ${{ secrets.FRP_SERVER_ADDR }}
  FRP_SERVER_PORT: ${{ secrets.FRP_SERVER_PORT }}
  FRP_TOKEN: ${{ secrets.FRP_TOKEN }}
  REMOTE_PORT: 20039

jobs:
  debug:
    name: Debug github Action with frp tunnel
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Debug github Action with frp tunnel
        uses: neighbads/frp-action-win@main
        with:
          frp_server_addr: ${{ env.FRP_SERVER_ADDR }}
          frp_server_port: ${{ env.FRP_SERVER_PORT }}
          frp_token: ${{ env.FRP_TOKEN }}
          remote_port: ${{ env.REMOTE_PORT }}